/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Address {
  address1?: string;
  address2?: string;
  city?: string;
  country_code?: string;
  postal_code?: string;
  state?: string;
}
