/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Customer {
  custom_fields?: object;
  email_address: string;
  first_name: string;
  language: string;
  last_name: string;
  status: string;
  tags?: string[];
}
