/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Member {
  custom_fields?: {
    /**
     * Unknown Property
     */
    [x: string]: unknown;
  };
  email_address: string;
  language: 'en' | 'ar' | 'af' | 'be' | 'bg' | 'ca' | 'zh' | 'hr' | 'cs' | 'da' | 'nl' | 'et' | 'fa' | 'fi' | 'fr' | 'fr_CA' | 'de' | 'el' | 'he' | 'hi' | 'hu' | 'is' | 'id' | 'ga' | 'it' | 'ja' | 'km' | 'ko' | 'lv' | 'lt' | 'mt' | 'ms' | 'mk' | 'no' | 'pl' | 'pt' | 'pt_PT' | 'ro' | 'ru' | 'sr' | 'sk' | 'sl' | 'es' | 'es_ES' | 'sw' | 'sv' | 'ta' | 'th' | 'tr' | 'uk' | 'vi';
  list_ids: string[];
  status: 'subscribed' | 'unsubscribed' | 'transactional';
  tags?: string[];
}
