/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Order {
  billing_address?: {
    address1?: string;
    address2?: string;
    city?: string;
    company?: string;
    country_code?: string;
    name?: string;
    phone?: string;
    postal_code?: string;
    state?: string;
  };
  cancelled_at?: string;
  created_at?: string;
  currency_code?: 'USD' | 'EUR' | 'GBP' | 'AUD' | 'INR' | 'NZD' | 'BRL' | 'DKK' | 'SEK' | 'SGD' | 'ZAR' | 'CHF' | 'MXN' | 'CAD' | 'HKD' | 'JPY';
  customer: {
    address?: {
      address1?: string;
      address2?: string;
      city?: string;
      country_code?: string;
      postal_code?: string;
      state?: string;
    };
    company?: string;
    email_address: string;
    first_name?: string;
    id: string;
    last_name?: string;
    status?: 'subscribed' | 'unsubscribed' | 'transactional';
  };
  discount_total?: number;
  financial_status?: 'paid' | 'pending' | 'refunded' | 'cancelled';
  fulfillment_status?: 'shipped' | 'pending' | 'cancelled';
  id: string;
  lines: {
    discount?: number;
    id: string;
    price?: number;
    product_id: string;
    product_variant_id: string;
    quantity?: number;
  }[];
  mailchimp_tracking_code?: string;
  order_total: number;
  order_url?: string;
  shipping_address?: {
    address1?: string;
    address2?: string;
    city?: string;
    company?: string;
    country_code?: string;
    name?: string;
    phone?: string;
    postal_code?: string;
    state?: string;
  };
  shipping_total?: number;
  store_id: string;
  tax_total?: number;
  tracking_carrier?: string;
  tracking_number?: string;
  tracking_url?: string;
  updated_at?: string;
}
