/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Product {
  description?: string;
  handle?: string;
  id: string;
  image_url?: string;
  published_at_foreign?: string;
  store_id: string;
  title: string;
  type?: string;
  url?: string;
  variants: ({
    id: string;
    image_url?: string;
    inventory_quantity?: number;
    price?: number;
    sku?: string;
    title: string;
    url?: string;
    visibility?: 'visible' | 'hidden';
  })[];
  vendor?: string;
}
