/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ServerSync {
  paths: {
    customers?: string;
    members?: string;
    orders?: string;
    products?: string;
    site?: string;
    store?: string;
  };
  reader?: string;
  writers: {
    fake?: {
      key?: string;
    };
    mailchimp?: {
      key?: string;
    };
  };
}
