/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Store {
  currency_code?: 'USD' | 'EUR' | 'GBP' | 'AUD' | 'INR' | 'NZD' | 'BRL' | 'DKK' | 'SEK' | 'SGD' | 'ZAR' | 'CHF' | 'MXN' | 'CAD' | 'HKD' | 'JPY';
  id: string;
  list_id: string;
  name: string;
}
