/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Store {
  currency_code?: string;
  id: string;
  list_id: string;
  name: string;
}
